/**
 * Browser PTGui ZIP export (img1.jpg … img36.jpg + manifest.json).
 * Naming follows https://github.com/sihagm/makeRGB
 */
import JSZip from "jszip";
import type { ManifestCamera, UpfManifest } from "@/lib/manifest";
import { mergeChannelJpegs, hasBayerChannels } from "@/lib/upf-client";
import { fetchUpfArrayBuffer } from "@/lib/fetch-upf-client";

const README = `Panono UPF → PTGui image export
================================

36 RGB JPEGs (img1.jpg … img36.jpg) from a Panono UPF.
See docs/reference/ptgui-export.md in the Panono Control webapp repo.

Generated by Panono Control webapp (browser export).
`;

async function exportCameraJpeg(zip: JSZip, cam: ManifestCamera): Promise<Blob | null> {
  const files = cam.imageFilenames ?? [];

  // Full UPF: demosaic the half-res Bayer planes to full-res RGB.
  if (hasBayerChannels(files)) {
    return mergeChannelJpegs(zip, files);
  }

  const previewName = files.find((f) => !/_red|_green|_blue/i.test(f));
  if (previewName) {
    const file = zip.file(previewName);
    return file ? file.async("blob") : null;
  }

  return mergeChannelJpegs(zip, files);
}

export async function downloadPtGuiZip(
  upfUrl: string,
  imageId: string,
  downloadFilename?: string
): Promise<void> {
  const zip = await JSZip.loadAsync(await fetchUpfArrayBuffer(upfUrl));
  const manifestFile = zip.file("manifest.json");
  if (!manifestFile) throw new Error("manifest.json not found in UPF");

  const manifest = JSON.parse(await manifestFile.async("string")) as UpfManifest;
  const setId = manifest.defaultSetId ?? 0;
  const cameras = (
    manifest.imageSets?.[setId]?.cameras ?? manifest.imageSets?.[0]?.cameras ?? []
  )
    .slice()
    .sort((a, b) => a.id - b.id);

  if (!cameras.length) throw new Error("No cameras in manifest");

  const outZip = new JSZip();
  let exported = 0;
  for (const cam of cameras) {
    const jpeg = await exportCameraJpeg(zip, cam);
    if (!jpeg) continue;
    outZip.file(`img${cam.id}.jpg`, jpeg);
    exported++;
  }
  if (!exported) throw new Error("No camera images could be exported");

  outZip.file("manifest.json", await manifestFile.async("string"));
  outZip.file("README.txt", README);

  const blob = await outZip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const objectUrl = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = objectUrl;
  a.download = downloadFilename ?? `${imageId}-ptgui-full.zip`;
  a.click();
  URL.revokeObjectURL(objectUrl);
}
