/**
 * Browser PTGui ZIP export (img1.jpg … img36.jpg + manifest.json).
 * Naming follows https://github.com/sihagm/makeRGB
 */
import JSZip from "jszip";
import type { ManifestCamera, UpfManifest } from "@/lib/manifest";
import { mergeChannelJpegs } from "@/lib/upf-client";
import { fetchUpfArrayBuffer } from "@/lib/fetch-upf-client";

const README = `Panono UPF → PTGui image export
================================

36 RGB JPEGs (img1.jpg … img36.jpg) from a Panono UPF.
See docs/reference/ptgui-export.md in the Panono Control webapp repo.

Generated by Panono Control webapp (browser export).
`;

async function exportCameraJpeg(zip: JSZip, cam: ManifestCamera): Promise<Blob | null> {
  const files = cam.imageFilenames ?? [];
  const previewName = files.find((f) => !/_red|_green|_blue/i.test(f));

  if (previewName) {
    const file = zip.file(previewName);
    return file ? file.async("blob") : null;
  }

  const find = (tag: string) => files.find((f) => f.includes(tag));
  const redName = find("_red");
  const greenName = find("_green0");
  const blueName = find("_blue");
  if (!redName || !greenName || !blueName) {
    return mergeChannelJpegs(zip, files);
  }

  const redF = zip.file(redName);
  const g0F = zip.file(greenName);
  const blueF = zip.file(blueName);
  if (!redF || !g0F || !blueF) return null;

  const [rBmp, g0Bmp, bBmp] = await Promise.all(
    [redF, g0F, blueF].map(async (f) => createImageBitmap(await f.async("blob")))
  );

  const w = rBmp.width;
  const h = rBmp.height;
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  const tmp = document.createElement("canvas");
  tmp.width = w;
  tmp.height = h;
  const tctx = tmp.getContext("2d");
  if (!tctx) return null;

  const out = ctx.createImageData(w, h);
  const rPx = grayChannel(tctx, rBmp);
  const gPx = grayChannel(tctx, g0Bmp);
  const bPx = grayChannel(tctx, bBmp);
  for (let i = 0, p = 0; i < w * h; i++, p += 4) {
    out.data[p] = rPx[i];
    out.data[p + 1] = gPx[i];
    out.data[p + 2] = bPx[i];
    out.data[p + 3] = 255;
  }
  ctx.putImageData(out, 0, 0);
  rBmp.close();
  g0Bmp.close();
  bBmp.close();

  return new Promise((resolve) => canvas.toBlob((b) => resolve(b), "image/jpeg", 0.92));
}

function grayChannel(tctx: CanvasRenderingContext2D, bmp: ImageBitmap): Uint8Array {
  tctx.drawImage(bmp, 0, 0);
  const data = tctx.getImageData(0, 0, bmp.width, bmp.height).data;
  const gray = new Uint8Array(bmp.width * bmp.height);
  for (let i = 0, j = 0; i < data.length; i += 4, j++) gray[j] = data[i];
  return gray;
}

export async function downloadPtGuiZip(upfUrl: string, imageId: string): Promise<void> {
  const zip = await JSZip.loadAsync(await fetchUpfArrayBuffer(upfUrl));
  const manifestFile = zip.file("manifest.json");
  if (!manifestFile) throw new Error("manifest.json not found in UPF");

  const manifest = JSON.parse(await manifestFile.async("string")) as UpfManifest;
  const setId = manifest.defaultSetId ?? 0;
  const cameras = (
    manifest.imageSets?.[setId]?.cameras ?? manifest.imageSets?.[0]?.cameras ?? []
  )
    .slice()
    .sort((a, b) => a.id - b.id);

  if (!cameras.length) throw new Error("No cameras in manifest");

  const outZip = new JSZip();
  let exported = 0;
  for (const cam of cameras) {
    const jpeg = await exportCameraJpeg(zip, cam);
    if (!jpeg) continue;
    outZip.file(`img${cam.id}.jpg`, jpeg);
    exported++;
  }
  if (!exported) throw new Error("No camera images could be exported");

  outZip.file("manifest.json", await manifestFile.async("string"));
  outZip.file("README.txt", README);

  const blob = await outZip.generateAsync({ type: "blob", compression: "DEFLATE" });
  const objectUrl = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = objectUrl;
  a.download = `${imageId}-ptgui-full.zip`;
  a.click();
  URL.revokeObjectURL(objectUrl);
}
