/**
 * Export Panono UPF sensor JPEGs as a ZIP for PTGui.
 *
 * Naming follows the reference exporter:
 * https://github.com/sihagm/makeRGB  →  img1.jpg … img36.jpg
 */
import JSZip from "jszip";
import sharp from "sharp";
import type { ManifestCamera, UpfManifest } from "@/lib/manifest";

const README = `Panono UPF → PTGui image export
================================

This ZIP contains 36 RGB JPEGs (img1.jpg … img36.jpg) extracted from a Panono UPF,
using the same naming convention as the makeRGB reference tool:

  https://github.com/sihagm/makeRGB

Full-resolution UPFs merge separate _red, _green0, and _blue channel JPEGs
(see makeRGB.py). Preview UPFs use the combined per-camera JPEGs as-is.

Also included: manifest.json (per-camera calibration from the UPF).

PTGui workflow
--------------
1. Add all img*.jpg files to a new PTGui project.
2. Set lens type to Rectilinear (~1863 px focal length, 2064×1552).
3. File → Apply Template (use a Panono .pts template — see PTGui forum).
4. Project → Align Images, then Create Panorama (equirectangular).

See docs/reference/ptgui-export.md in the Panono Control webapp repo.

Generated by Panono Control webapp.
`;

export async function buildStitcherZipFromUpf(upfBuf: Buffer): Promise<Buffer> {
  const zip = await JSZip.loadAsync(upfBuf);
  const manifestFile = zip.file("manifest.json");
  if (!manifestFile) throw new Error("manifest.json not found in UPF");

  const manifest = JSON.parse(await manifestFile.async("string")) as UpfManifest;
  const setId = manifest.defaultSetId ?? 0;
  const cameras = (
    manifest.imageSets?.[setId]?.cameras ?? manifest.imageSets?.[0]?.cameras ?? []
  ).slice().sort((a, b) => a.id - b.id);

  if (!cameras.length) throw new Error("No cameras in manifest");

  const outZip = new JSZip();
  let exported = 0;

  for (const cam of cameras) {
    const jpeg = await exportCameraJpeg(zip, cam);
    if (!jpeg) continue;
    outZip.file(`img${cam.id}.jpg`, jpeg);
    exported++;
  }

  if (!exported) throw new Error("No camera images could be exported");

  outZip.file("manifest.json", await manifestFile.async("string"));
  outZip.file("README.txt", README);

  return outZip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });
}

/** makeRGB-style RGB merge: R + green0 + B (not green1 average). */
async function exportCameraJpeg(zip: JSZip, cam: ManifestCamera): Promise<Buffer | null> {
  const files = cam.imageFilenames ?? [];
  const previewName = files.find((f) => !/_red|_green|_blue/i.test(f));

  if (previewName) {
    const file = zip.file(previewName);
    if (!file) return null;
    const buf = await file.async("nodebuffer");
    return sharp(buf).jpeg({ quality: 92, mozjpeg: true }).toBuffer();
  }

  const find = (tag: string) => files.find((f) => f.includes(tag));
  const redName = find("_red");
  const greenName = find("_green0");
  const blueName = find("_blue");
  if (!redName || !greenName || !blueName) return null;

  const [rBuf, gBuf, bBuf] = await Promise.all(
    [redName, greenName, blueName].map(async (n) => {
      const f = zip.file(n!);
      return f ? f.async("nodebuffer") : null;
    })
  );
  if (!rBuf || !gBuf || !bBuf) return null;

  const [r, g, b] = await Promise.all(
    [rBuf, gBuf, bBuf].map((buf) => grayRaw(buf))
  );
  const width = r.width;
  const height = r.height;
  const rgb = Buffer.alloc(width * height * 3);
  for (let i = 0, j = 0; i < width * height; i++, j += 3) {
    rgb[j] = r.data[i]!;
    rgb[j + 1] = g.data[i]!;
    rgb[j + 2] = b.data[i]!;
  }

  return sharp(rgb, { raw: { width, height, channels: 3 } })
    .jpeg({ quality: 92, mozjpeg: true })
    .toBuffer();
}

async function grayRaw(
  buf: Buffer
): Promise<{ data: Uint8Array; width: number; height: number }> {
  const { data, info } = await sharp(buf).grayscale().raw().toBuffer({
    resolveWithObject: true,
  });
  return { data: new Uint8Array(data), width: info.width, height: info.height };
}
